services:
  # React 클라이언트 서비스
  client:
    build:
      context: ./react-client
      dockerfile: Dockerfile
    ports:
      # 호스트의 3000번 포트를 컨테이너의 80번 포트와 매핑
      - "3000:80"
    restart: unless-stopped
    depends_on:
      # proxy 서비스가 실행된 후에 client 서비스가 실행되도록 설정
      - proxy

  # Proxy 서버 서비스
  proxy:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      # 호스트의 5000번 포트를 컨테이너의 5000번 포트와 매핑
      - "5000:5000"
    restart: unless-stopped